### ISSUE TITLE
Would you please release 6.3.2?

### ISSUE THREAD

**Issue by matsumana** [codelibs/elasticsearch-analysis-kuromoji-neologd#11]
Hello.

I want to use elasticsearch-analysis-kuromoji-neologd with Elasticsearch 6.3.2
However, elasticsearch-analysis-kuromoji-neologd 6.3.2 has not been released.

Would you please release it?

**Comment by marevol** [comment]
You can use elasticsearch-analysis-kuromoji-neologd 6.3.1 on elasticsearch 6.3.x release.

**Comment by matsumana** [comment]
Got it.
Thank you.
